[
  {
    id: "fb24d7ee12bf326196320c16ffeb9635",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./source/Img/KarenDarbinyan.jpg",
  },
  {
    id: "825843dcb02507ea8028f50bfe0053d4",
    firstName: "Alexandr",
    lastName: "Hamabrdzumyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./source/Img/AlexandrHamabrdzumyan.jpg",
  },
  {
    id: "c7bb32cf17770c8f848332755665db7e",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./source/Img/HasmikGevorgyan.jpg",
  },
  {
    id: "ca385da57c516314d3fb55ecdffa3ba7",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./source/Img/LusineYeremyan.jpg",
  },
  {
    id: "9512f3ba13f09ac3ca176e8e05697c29",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./source/Img/AnahitKhechumyan.jpg",
  },
  {
    id: "a27953ec755dc6dea3fbc3790a723f56",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "-----",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "RELQ",
    imagePath: "./source/Img/AniAntonyan.jpg",
  },
  {
    id: "c60ce958a795dfa0abefde4e28a7ead0",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "+374 98 14 44 50",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
    imagePath: "./source/Img/AnnaHayriyan.jpg",
  },
  {
    id: "aa1f8a2500b91426f28b3d27be52e115",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: "+374 94 90 21 71",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
    imagePath: "./source/Img/ArmenakQocharyan.jpg",
  },
  {
    id: "d5ba1187a1cef064d05799c3fdd74bf0",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "+374 55 90 01 55",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:
      "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
    imagePath: "./source/Img/ArusyakAghajanyan.jpg",
  },
  {
    id: "9cc63eab0008d680bceced0fd7059a94",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "-----",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/Img/AfinaPanyan.jpg",
  },
  {
    id: "93d51cb1a3f2a24ce05c980ae9866b42",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "+374 93 28 55 95",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/Img/BabkenTadevosyan.jpg",
  },
  {
    id: "a496e3290b1b271ebcf93e4f6dc5d87b",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "-----",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/Img/HermineMelkumyan.jpg",
  },
  {
    id: "fbec1213dfb4d1ad951d388fa2e688f8",
    firstName: "Hermine",
    lastName: "Sahakyan",
    phone: "-----",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/Img/HermineSahakyan.jpg",
  },
  {
    id: "9a47dc42b38ea4a3c60f60fa181c67da",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: "+374 97 75 95 99",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
    imagePath: "./source/Img/LarineDanielyan.jpg",
  },
  {
    id: "90d88bea0d27a3caeec7962ea3cea89f",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "+374 91 55 53 74",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
    imagePath: "./source/Img/LianaDashyan.jpg",
  },
  {
    id: "efccee311faedb63bdd122d3a702073d",
    firstName: "Lusya",
    lastName: "Petrosyan",
    phone: "+374 93 32 29 02",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/Img/LusyaPetrosyan.jpg",
  },
  {
    id: "e506dafc16ecd850aaab3bf76202e287",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: "+374 44 05 51 50",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
    imagePath: "./source/Img/MaratHarutyunyan.jpg",
  },
  {
    id: "cfef2f4b0454992e82e18ceda34000f7",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "+374 94 27 67 00",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
    imagePath: "./source/Img/NarekTovmasyan.jpg",
  },
  {
    id: "a89dadb5360eb987d09ec1e2e0d9f912",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "+374 98 31 38 71",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "-----",
    trainings: "TechBoost4Women,RELQ technology school",
    imagePath: "./source/Img/SedaShahnazaryan.jpg",
  },
  {
    id: "f37982fd66b8497a9a46b9bc8f12cd1e",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "+374 94 24 68 80",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/Img/SeryozhaAsatryan.jpg",
  },
  {
    id: "85dee05cdc53a3f2a54407ace6a29a2f",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "+374 77 12 16 96",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/Img/SevakStepanyan.jpg",
  },
  {
    id: "b6437695d3a388beb2e8dbd3d123d2e6",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "-----",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/Img/SilvaOhanyan.jpg",
  },
  {
    id: "e7a319c7d1e9d228f61fd86dc881e7ca",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "-----",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/Img/SurenGalstyan.jpg",
  },
  {
    id: "8ff939c047277f9ca5a5e0abd23bc7c7",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "+374 77 15 18 68",
    email: "martirosyant01@mail.ru",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/Img/TigranMartirosyan.jpg",
  },
  {
    id: "8ff939c047277f9ca5a5e0abd23bc7c7",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "+374 77 15 18 68",
    email: "martirosyant01@mail.ru",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/Img/TigranMartirosyan.jpg",
  },
];
